### ISSUE TITLE
"Files missing summary" table needs to be taller

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#200] opened 2019-07-08 09:25 UTC
From 0.4.0-beta.1

![image](https://user-images.githubusercontent.com/1469173/60799198-9cc0d800-a16a-11e9-9515-cf0d422a20b5.png)

**Comment by dpordomingo** [comment] 2019-07-08 09:38
If I'm not wrong, this is a dupe of https://github.com/src-d/sourced-ui/issues/118
that should be fixed by https://github.com/src-d/sourced-ui/pull/187
Could you confirm if you loaded the new charts provided by https://github.com/src-d/sourced-ui/pull/187?

**Comment by smacker** [comment] 2019-07-08 10:50
this pr https://github.com/src-d/sourced-ui/pull/189 overridden it. Merge of the fix and commit with an update for all dashboards were made on the same day.

**Closed** 2019-07-08 16:52 UTC
