### ISSUE TITLE
Provide a way to export/import dashboards

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#165] opened 2019-06-24 17:44 UTC
The current way requires manual editing, is very tedious, slow, and error prone.

**Comment by smacker** [comment] 2019-06-24 18:00
I would change the title to "implement". You can't "find" it.

**Comment by smacker** [comment] 2019-06-25 13:46
We discussed few solutions for the problem and decided to write a DD first.
For that, we need to do more investigation first.

**Comment by smacker** [comment] 2019-06-26 16:34
Intermidiate results of investigation: https://gist.github.com/smacker/99899e2246648c2d44fa85e60d3e23ec

TL;DR: I managed to fix it and validated with UI import/export, diff is here: https://github.com/src-d/sourced-ui/pull/171

The DD will be created later.

**Comment by smacker** [comment] 2019-06-27 12:23
DD: https://docs.google.com/document/d/1vfiAw7yCzqvb3ALo_aiBX3XFPjLNZ1Mira-X7HCK1lI

**Comment by smacker** [comment] 2019-07-09 14:17
Everything was implemented and most of the PRs merged:

- https://github.com/src-d/sourced-ui/pull/180
- https://github.com/src-d/sourced-ui/pull/189
- https://github.com/src-d/sourced-ui/pull/190
- https://github.com/src-d/sourced-ui/pull/197
- https://github.com/src-d/sourced-ui/pull/198
- https://github.com/src-d/sourced-ui/pull/203
- https://github.com/src-d/sourced-ui/pull/205

I'll keep this issue open to track the status of integrating it into upstream.

**Comment by smacker** [comment] 2019-07-16 17:58
The first PR into upstream: https://github.com/apache/incubator-superset/pull/7879
It took a while to figure out why cache tests were failing.
In our fork those tests weren't failing because occasionally previous changes to `import_export_tests` produced absolutely the same effect as described in the PR (deleting slices on `tearDownClass`).

**Comment by smacker** [comment] 2019-07-17 10:15
apache/incubator-superset#7879 was rebased to incorporate changes made by just merged https://github.com/apache/incubator-superset/pull/7773

New PR for sorting keys submitted: https://github.com/apache/incubator-superset/pull/7883

**Comment by smacker** [comment] 2019-07-18 13:54
The PRs from above were merged. 2 more PRs created:

1. Fix regression in master (introduced by rework of examples which affected import/export) https://github.com/apache/incubator-superset/pull/7892
2. Set owner to dashboards and charts on import https://github.com/apache/incubator-superset/pull/7894

The most important change of remote_id from integer id to uuid id still pending. Upstream has work-in-progress PR which adds uuids as a new DB field. We can reuse it. But I would prefer to keep using json field at least for now to avoid migration.

**Comment by Aylr** [comment] 2019-07-19 03:26
@smacker Thanks for the excellent work on this. Please lmk how I can help on any of this - these issues are blocking faster deploys for me.

**Comment by smacker** [comment] 2019-07-23 08:29
The PRs from above are merged. I'll start working on adapting uuid change to upstream master as soon as I finish with current demos.

@Aylr if you need this change asap you can try to apply #189 and #197 on superset master in our own fork.

**Comment by smacker** [comment] 2019-07-24 11:09
After more consideration, I think it's better to wait for https://github.com/apache/incubator-superset/pull/7829 to land in master and improve on top of it if necessary. (in the current state of PR uuids are used only for datasources and not slices/dashboards, not sure if slices/dashs will be covered in the same pr later or not).

**Comment by se7entyse7en** [comment] 2019-10-02 13:25
I just noticed that the PR upstream that you mentioned is stale, what does that exactly add? I mean AFAIK import/export for our use-cases already works except for some bugs such as #288.

**Comment by se7entyse7en** [comment] 2019-10-18 14:01
@smacker are you aware of other bugs/improvements that are missing before closing this?

**Comment by smacker** [comment] 2019-10-18 14:15
I think we can close it as it works in sourced-ui.
One day the change in the upstream will be made then we can rework our implementation but for now we are good.

**Closed** 2019-10-18 14:17 UTC
Labels: enhancement
